// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVoYn6_mdzk8pggQcq64xNjGlQtEnQh4U',
    appId: '1:1073259310249:web:1462c143a5c86814bc0db8',
    messagingSenderId: '1073259310249',
    projectId: 'peaceful-region-351707',
    authDomain: 'peaceful-region-351707.firebaseapp.com',
    storageBucket: 'peaceful-region-351707.appspot.com',
    measurementId: 'G-GLG5LMH70J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe-fKEiGxfaEhE-YLQAoepW-BQob-litg',
    appId: '1:1073259310249:android:d0d0344ebd34b181bc0db8',
    messagingSenderId: '1073259310249',
    projectId: 'peaceful-region-351707',
    storageBucket: 'peaceful-region-351707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWK3Ae89e31ATfMmxTtguIjBk0JwhcoTw',
    appId: '1:1073259310249:ios:378061d59ca7eb50bc0db8',
    messagingSenderId: '1073259310249',
    projectId: 'peaceful-region-351707',
    storageBucket: 'peaceful-region-351707.appspot.com',
    iosClientId: '1073259310249-p7lj7j7nb80gjshoosvt117socmqn99s.apps.googleusercontent.com',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWK3Ae89e31ATfMmxTtguIjBk0JwhcoTw',
    appId: '1:1073259310249:ios:31942617c6cfbe6dbc0db8',
    messagingSenderId: '1073259310249',
    projectId: 'peaceful-region-351707',
    storageBucket: 'peaceful-region-351707.appspot.com',
    iosClientId: '1073259310249-e92a8k7mjcjjfqunf72i8hcrgq4kfni2.apps.googleusercontent.com',
    iosBundleId: 'com.example.first.RunnerTests',
  );
}
